source 'https://rubygems.org'

gem 'rspec', '~> 3.7'
gem 'capybara', '~> 2.7', '>= 2.7.1'
gem 'selenium-webdriver', '~> 3.6'
gem 'httparty', '~> 0.15.6'
gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'pg', '>= 0.19.0.beta'